In [16]:
import io
import sys
PATH = "D:/OneDrive - Universidad Tecnológica de Bolívar/Apps\MachineLearning-ISCO-A14A/"
DIR_DATA = PATH + "data/"
sys.path.append(PATH) if PATH not in list(sys.path) else None
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
from sklearn.preprocessing import LabelEncoder 
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.feature_extraction.text import CountVectorizer
from logic.text_processing import TextProcessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

In [17]:
tp = TextProcessing()
le = LabelEncoder()

In [18]:
raw_data = pd.read_csv(DIR_DATA + 'TASS2018.csv', sep=';')
raw_data

tweetid            user  \
0    770976639173951488    noseashetero   
1    771092421866389508        Templelx   
2    771092111429083136        esskuu94   
3    771092070572449796      __ariadna9   
4    771094192508600320   _cristtina15_   
..                  ...             ...   
501  757593585634213888       RubenRuCh   
502  757585725764362240        rayjaken   
503  757097408304148480         Fuhyo__   
504  757971881077182464  xLytherinDovah   
505  757949870124695552      ShiraPamer   

                                               content              date lang  \
0    @noseashetero 1000/10 de verdad a ti que voy a...  31/08/2016 13:28   es   
1    @piscolabisaereo @HistoriaNG @SPosteguillo las...  31/08/2016 21:08   es   
2    Al final han sido 3h  Bueno, mañana tengo fies...  31/08/2016 21:07   es   
3    @Jorge_Ruiz14 yo no tengo tiempo para esas cos...  31/08/2016 21:07   es   
4    @_MissChaotic_ ves ese brillo? es un coso que ...  31/08/2016 21:15   es   
..                                                 ...               ...  ...   
501               @Davorias Pero es que está muy rica   25/07/2016 15:09   es   
502                     @narvalillo Eso es antiguo ya   25/07/2016 14:38   es   
503                    Mi TL esta vacía a estas horas    24/07/2016 6:17   es   
504  Ya tengo uno, pero ese es más cheto  @aweamasome.  26/07/2016 16:12   es   
505                 Estoy sensible y lloro por todo y   26/07/2016 14:45   es   

    polarity  
0          P  
1          P  
2          P  
3          N  
4          N  
..       ...  
501        P  
502        N  
503        N  
504      NEU  
505        N  

[506 rows x 6 columns]

In [19]:
y = le.fit_transform(raw_data['polarity'])
y

array([3, 3, 3, 0, 0, 3, 1, 2, 2, 3, 3, 2, 0, 2, 2, 0, 3, 3, 3, 0, 0, 1,
       0, 0, 0, 0, 1, 3, 1, 3, 0, 0, 1, 2, 0, 3, 3, 0, 0, 0, 0, 3, 0, 3,
       1, 3, 3, 1, 0, 3, 3, 3, 0, 0, 3, 1, 0, 0, 0, 3, 0, 2, 0, 3, 0, 3,
       2, 0, 3, 1, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3,
       1, 3, 0, 3, 0, 0, 0, 0, 1, 3, 0, 1, 1, 2, 0, 1, 3, 3, 0, 3, 3, 1,
       3, 3, 0, 0, 1, 0, 3, 0, 0, 0, 1, 3, 0, 1, 3, 1, 3, 2, 1, 1, 0, 2,
       1, 3, 3, 3, 1, 0, 0, 0, 3, 3, 1, 3, 3, 0, 3, 3, 0, 3, 0, 1, 0, 2,
       2, 0, 3, 2, 1, 0, 3, 0, 0, 3, 0, 0, 3, 3, 3, 0, 3, 0, 0, 2, 3, 3,
       0, 2, 0, 3, 1, 3, 1, 0, 0, 2, 0, 2, 0, 0, 1, 2, 3, 3, 3, 1, 3, 3,
       0, 1, 3, 3, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0, 2, 3, 3, 3, 0, 1, 3,
       0, 0, 2, 3, 0, 3, 3, 1, 2, 3, 3, 3, 0, 0, 3, 0, 3, 2, 0, 0, 0, 2,
       0, 0, 0, 3, 1, 0, 3, 0, 3, 2, 3, 0, 0, 3, 3, 0, 0, 3, 0, 1, 0, 3,
       3, 2, 0, 0, 2, 3, 2, 1, 3, 3, 2, 3, 0, 1, 1, 0, 0, 2, 1, 0, 3, 1,
       1, 3, 0, 0, 1, 2, 2, 2, 2, 3, 0, 0, 0, 3, 0,

In [20]:
corpus = [tp.transformer(row) for row in raw_data['content'].tolist()]
len(corpus), len(y)

(506, 506)

In [21]:
bow = CountVectorizer(analyzer='word', ngram_range=(1, 1))

In [22]:
x = bow.fit_transform(corpus)

In [23]:
x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
df = pd.DataFrame(x.toarray(),
                  index=['content '+str(i) for i in range(1, 1+len(corpus))],
                  columns=bow.get_feature_names())

In [25]:
df

1030  11s  15  15s  16  17  178  18  20  21  ...  xv  ya  ye  yo  \
content 1       0    0   0    0   0   0    0   0   0   0  ...   0   0   0   0   
content 2       0    0   0    0   0   0    0   0   0   0  ...   0   0   0   0   
content 3       0    0   0    0   0   0    0   0   0   0  ...   0   0   0   0   
content 4       0    0   0    0   0   0    0   0   0   0  ...   0   0   0   1   
content 5       0    0   0    0   0   0    0   0   0   0  ...   0   0   0   0   
...           ...  ...  ..  ...  ..  ..  ...  ..  ..  ..  ...  ..  ..  ..  ..   
content 502     0    0   0    0   0   0    0   0   0   0  ...   0   0   0   0   
content 503     0    0   0    0   0   0    0   0   0   0  ...   0   1   0   0   
content 504     0    0   0    0   0   0    0   0   0   0  ...   0   0   0   0   
content 505     0    0   0    0   0   0    0   0   0   0  ...   0   1   0   0   
content 506     0    0   0    0   0   0    0   0   0   0  ...   0   0   0   0   

             youtube  zack  zi  zona  zonas  zoy  
content 1          0     0   0     0      0    0  
content 2          0     0   0     0      0    0  
content 3          0     0   0     0      0    0  
content 4          0     0   0     0      0    0  
content 5          0     0   0     0      0    0  
...              ...   ...  ..   ...    ...  ...  
content 502        0     0   0     0      0    0  
content 503        0     0   0     0      0    0  
content 504        0     0   0     0      0    0  
content 505        0     0   0     0      0    0  
content 506        0     0   0     0      0    0  

[506 rows x 2215 columns]

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [40]:
x_train

<354x2215 sparse matrix of type '<class 'numpy.int64'>'
	with 4749 stored elements in Compressed Sparse Row format>

In [41]:
softmax = LogisticRegression(multi_class="multinomial", solver="lbfgs", C=10)

In [42]:
softmax.fit(x_train, y_train)

LogisticRegression(C=10, multi_class='multinomial')

In [43]:
Counter(y_test)

Counter({2: 22, 0: 74, 3: 39, 1: 17})

In [44]:
y_predict = softmax.predict(x_test)
y_predict

array([0, 0, 0, 3, 3, 0, 0, 3, 0, 0, 0, 0, 1, 3, 3, 0, 3, 0, 3, 3, 3, 0,
       0, 1, 0, 0, 0, 0, 3, 1, 3, 0, 3, 3, 3, 0, 0, 3, 3, 3, 0, 0, 0, 3,
       0, 0, 0, 0, 0, 3, 3, 0, 1, 1, 0, 0, 3, 0, 0, 0, 0, 3, 3, 0, 3, 0,
       3, 0, 0, 3, 0, 0, 0, 3, 1, 0, 3, 0, 3, 0, 1, 3, 3, 0, 0, 0, 0, 2,
       0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 0, 3, 1, 3,
       3, 3, 3, 3, 1, 3, 0, 0, 0, 3, 0, 0, 3, 0, 0, 3, 0, 0, 0, 0, 3, 0,
       0, 3, 0, 3, 3, 0, 3, 0, 0, 1, 3, 3, 2, 0, 0, 3, 0, 3, 3, 0])

In [45]:
confusion_matrix(y_test, y_predict, labels=[0, 1, 2, 3])

array([[50,  6,  1, 17],
       [ 8,  2,  0,  7],
       [14,  1,  1,  6],
       [14,  1,  1, 23]], dtype=int64)

In [46]:
classification = classification_report(y_test, y_predict)
print(classification)

              precision    recall  f1-score   support

           0       0.58      0.68      0.63        74
           1       0.20      0.12      0.15        17
           2       0.33      0.05      0.08        22
           3       0.43      0.59      0.50        39

    accuracy                           0.50       152
   macro avg       0.39      0.36      0.34       152
weighted avg       0.47      0.50      0.46       152

